ALTER TABLE fb_users
ADD COLUMN `access_token` VARCHAR(250),
ADD COLUMN `last_login_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN `sign_up_time` TIMESTAMP DEFAULT current_timestamp

